CREATE SEQUENCE HR.INSTALLEMENTS_PAID_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
CREATE OR REPLACE TRIGGER HR.INSTALLEMENTS_PAID_TRG
BEFORE INSERT
ON HR.INSTALLEMENTS_PAID 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column INSTALLEMENTS_ID
  :new.INSTALLEMENTS_ID := INSTALLEMENTS_PAID_SEQ.nextval;
END INSTALLEMENTS_PAID_TRG;