CREATE TABLE HR.INSTALLEMENTS_PAID
(
  INSTALLEMENTS_ID      NUMBER,
  CONTRACT_ID           NUMBER,
  INSTALLEMENTS_DATE    DATE,
  INSTALLEMENTS_AMOUNT  NUMBER(10,2),
  PAID                  NUMBER
);
ALTER TABLE HR.INSTALLEMENTS_PAID ADD (
  CONSTRAINT INSTALLEMENTS_PAID_PK
 PRIMARY KEY
 (INSTALLEMENTS_ID));